# Generated by Django 4.2.7 on 2023-11-22 15:07

from django.db import migrations, models
import xpoarena.models


class Migration(migrations.Migration):

    dependencies = [
        ('xpoarena', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booth',
            name='image',
            field=models.ImageField(default='posts/default.jpg', upload_to=xpoarena.models.upload_to, verbose_name='Image'),
        ),
    ]
