# Generated by Django 4.2.7 on 2023-12-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpoarena', '0005_alter_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(choices=[('RPG', 'Role Playing Game'), ('Action', 'Action'), ('Adventure', 'Adventure'), ('Puzzle', 'Puzzle'), ('Sports', 'Sports'), ('Casual', 'Causal'), ('Shooting', 'Shooting')], default='RPG', max_length=255),
        ),
    ]
