# Generated by Django 4.2.7 on 2023-12-11 22:15

from django.db import migrations, models
import xpoarena.models


class Migration(migrations.Migration):

    dependencies = [
        ('xpoarena', '0008_alter_game_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('theme_video', models.FileField(blank=True, null=True, upload_to=xpoarena.models.upload_to)),
                ('font_name', models.CharField(max_length=255)),
                ('font_color', models.CharField(max_length=10)),
            ],
        ),
    ]
