# Generated by Django 4.2.7 on 2023-12-11 22:36

from django.db import migrations, models
import xpoarena.models


class Migration(migrations.Migration):

    dependencies = [
        ('xpoarena', '0009_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='theme_video',
            field=models.FileField(upload_to=xpoarena.models.upload_to),
        ),
    ]
