# Generated by Django 4.2.7 on 2023-12-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpoarena', '0015_alter_game_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image_url',
            field=models.URLField(max_length=1000),
        ),
    ]
