# Generated by Django 4.2.7 on 2024-03-31 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpoarena', '0020_userprofile_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='secret_key',
            field=models.CharField(default='temp-secret-key', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
