# Generated by Django 4.2.7 on 2024-04-01 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xpoarena', '0022_paymenthistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenthistory',
            old_name='product',
            new_name='game',
        ),
    ]
