# Generated by Django 4.2.7 on 2024-05-08 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import xpoarena.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xpoarena', '0024_conversation_conversationmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='xpoarena.game')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('dateOfEvent', models.DateField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('image', models.ImageField(upload_to=xpoarena.models.upload_to)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xpoarena.organization')),
            ],
        ),
    ]
